create table if not exists public.topup_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text,
  amount_rupiah bigint not null,
  gems_amount bigint not null,
  payment_method text, 
  status text default 'pending', 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Settings
alter table public.topup_requests enable row level security;

-- Policy can insert
create policy "Users can insert their own requests"
on public.topup_requests for insert
with check (auth.uid() = user_id);

-- Policy can view
create policy "Users can view their own requests"
on public.topup_requests for select
using (auth.uid() = user_id);
